### ISSUE TITLE
fatal: No url found for submodule path 'testapi/bin/cookbooks/testsamp'

### ISSUE THREAD

**Issue by torgeman** [go-chef/chef#200]
Once I try to install `go get github.com/go-chef/chef` I get:
```
fatal: No url found for submodule path 'testapi/bin/cookbooks/testsamp' in .gitmodules
package github.com/go-chef/chef: exit status 128
```

**Comment by MarkGibbons** [comment]
Thanks for the report.  I'm working on reproducing the error.

**Comment by MarkGibbons** [comment]
Sorry about that. I missed an embedded .git in the embedded cookbook used as input to a test. go get worked for me with the latest version of go-chef/chef.

**Comment by MarkGibbons** [comment]
Please let me know if you have problems or this fix doesn't work.  Cheers

**Comment by torgeman** [comment]
Looks good! 
10x
