### ISSUE TITLE
SearchResult#Rows should be an array of json.RawMessage and not empty interface

### ISSUE THREAD

**Issue by satyanash** [go-chef/chef#213]
We have a struct defined as:
```
type SearchResult struct {
	Total int
	Start int
	Rows  []interface{}
}
```

Here, `Rows` is an array of the empty `interface{}`. But we know that whatever item the server returns as the "rows", must be valid json. So we can make it stricter by specifying the type as `json.RawMessage`.
```
type SearchResult struct {
	Total int
	Start int
	Rows  []json.RawMessage
}
```

This way, it is also made faster and the caller can then cast the individual elements to whichever index type they've queried, instead of having to deal with a `map[string]interface{}`.

**Comment by MarkGibbons** [comment]
Thank you for opening the issue.

**Comment by MarkGibbons** [comment]
#239 addresses these concerns.  Sorry it took so long.
