### ISSUE TITLE
Unexpected `Access` field in the `Cookbook` structure

### ISSUE THREAD

**Issue by svagner** [go-chef/chef#221]
@afiune, @MarkGibbons could you please explain what does this `Access` field means here - https://github.com/go-chef/chef/blob/master/cookbook.go#L87.
I assume it should be compatible with APIs: https://docs.chef.io/server/api_chef_server/#get-23 and https://docs.chef.io/server/api_chef_server/#put-6

Please correct me if I'm wrong

**Comment by MarkGibbons** [comment]
To clarify one point, the chef doc for #get-23 says 

"Response

The response **is similar to**:"

The chef doc frequently leaves off bit and pieces and doesn't get updated very often.  I think I've written about a quarter of that api doc at this point and lightly edited a lot of the rest.  It's not a swagger definition or anything like that in terms of authority. 

I'm going try running the api against a chef server and see what gets returned for Access out of curiosity. One of the ways to figure it out is to see how the chef client uses the value. Look at the ruby code for the client or for knife and see what it does.

**Comment by MarkGibbons** [comment]
Using the  cookbooks GetVersion method I see that Access is returned for a cookbook from the chef server.
Access:{Read:false Create:false Grant:false Update:false Delete:false} in the example case (the example are in the testapi directory).  Those look like default ACL settings for the cookbook, guess though.
