### ISSUE TITLE
Search result object has changed structure in recent versions of Chef Infra server

### ISSUE THREAD

**Issue by hrak** [go-chef/chef#224]
The response of a search query on a recent version of Chef looks different than most of the tests in this package. It is an array of hash now with a`url` and `data` object in it.

Example:

```
{
	"total": 2,
	"start": 0,
	"rows": [{
		"url": "https://chef.example.com/organizations/exampleorg/nodes/es-data5.devp.dev.example.com",
		"data": {
			"name": "es-data5.devp.dev.example.com",
			"package_updates": {
				"ubuntu-advantage-tools": {
					"version": "27.5~18.04.1",
					"arch": "amd64"
				}
			}
		}
	}, {
		"url": "https://chef.example.com/organizations/exampleorg/nodes/es-master1.devp.dev.example.com",
		"data": {
			"name": "es-master1.devp.dev.example.com",
			"package_updates": {
				"ubuntu-advantage-tools": {
					"version": "27.5~18.04.1",
					"arch": "amd64"
				}
			}
		}
	}]
}
```

To get to the search results now requires a `pres.Rows[0].(map[string]interface{})["data"].(map[string]interface{})["package_updates"]` f.e.

PS i am a big fan of the pending PR's that allow access to search results using json instead of this `map[string]interface{}` method.

**Comment by MarkGibbons** [comment]
I'll take a look. What you have listed is supposed to be the response to a POST.  I'll have to see if GET changed too.  It looks like go-chef returns one struct for both GET and POST (partial search) which makes it use that nasty interface structure.

**Comment by hrak** [comment]
It only affects partial search (POST) indeed. See https://docs.chef.io/server/api_chef_server/#search

**Comment by MarkGibbons** [comment]
#239 should address the concerns.  The current search functions return interface{} structures and continue to work with changes to the returned structures.  #239 adds parsing that deals with the new return structure and returns raw json message format for data specific to each type of search item allowing for further processing as desired.
