### ISSUE TITLE
Error Types

### ISSUE THREAD

**Issue by spheromak** [go-chef/chef#49]
Adding richer errors and error types for all the services where it makes sense. Internally in http  possibly as well.

**Comment by gilzellner** [comment]
I'm guess its the same thing I want: to get the errorcode as a number when you try to delete a non existent node ?

**Comment by MarkGibbons** [comment]
I believe #189 addresses this issue adequately.  You can see the 404 response from the chef server fairly easily.  I add examples documenting the use that return a 409 caused by recreating an object.
