### ISSUE TITLE
Tests fail intermittently

### ISSUE THREAD

**Issue by jmallach** [go-chef/chef#87]
Hi!

The Debian build of go-chef/chef runs the test suite, and it has been found that it randomly fails.

```
=== RUN   TestClientsService_List
--- FAIL: TestClientsService_List (0.01s)
	client_test.go:47: Clients.List returned:
		client1 => http://localhost/clients/client1
		client2 => http://localhost/clients/client2
		
		want:
		client1 => http://localhost/clients/client1
		client2 => http://localhost/clients/client2
```

or
```
=== RUN   TestDataBagsService_DataBagListResultString
--- FAIL: TestDataBagsService_DataBagListResultString (0.00s)
	databag_test.go:162: DataBagListResult.String returned:
		bag1 => http://localhost/data/bag1
		bag2 => http://localhost/data/bag2
		
		want:
		bag1 => http://localhost/data/bag1
		bag2 => http://localhost/data/bag2
```

I can provide more info on request.

**Comment by jmallach** [comment]
Also, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=848055 for the Debian bug report.

**Comment by spheromak** [comment]
Interesting. Thanks for the report.

**Comment by MarkGibbons** [comment]
The String functions use for loop over a map which produces output in undefined order.

**Comment by MarkGibbons** [comment]
Not exactly the reported problem but it is one of the sources of random test failures.

**Comment by MarkGibbons** [comment]
It turns out the random order is what is causing the reported problem.
 if response.String() != want && response.String() != want2 {
                t.Errorf("Clients.List returned:\n%+v\nwant:\n%+v\n", response.String(), want)
        }

What gets displays and shows stuff that should match is from a different call to String() and is not what was checked in the if statement.

**Comment by MarkGibbons** [comment]
Should by fixed now.
