### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by sorcix** [go-chef/chef#95]
The new [`dep`](https://github.com/golang/dep) uses the latest [semver](http://semver.org/) tag by default. This means it downloads a very old version of `github.com/go-chef/chef`. It's possible to make `dep` use the master branch, but it would be easier you'd release versions more frequently.

**Comment by spheromak** [comment]
yep we should do this for sure. will get something into CI

**Comment by MarkGibbons** [comment]
Got code for this in circleci.  Will try it out on the next few merges.
